"""Pydantic schemas for every stage of the pipeline."""

from doc_extractor.schemas.attribute import (
    Attribute,
    AttributeCandidate,
    AttributeType,
    BindingScope,
    CandidateOrigin,
    EntityBinding,
    Optionality,
    Route,
    ScoreBreakdown,
    SignalHit,
)
from doc_extractor.schemas.chunk import Chunk
from doc_extractor.schemas.common import Evidence, Layer, Provenance, StrictModel, Unit, ValueDomain
from doc_extractor.schemas.document import (
    Block,
    BlockKind,
    Document,
    DocumentFormat,
    DocumentSummary,
    Page,
    Table,
)
from doc_extractor.schemas.entity import CanonicalEntity, Entity, EntityOrigin, NormalizedEntity
from doc_extractor.schemas.mapping import Mapping, RelationshipType
from doc_extractor.schemas.output import FinalOutput, ReviewSection, RunMetadata, TraceEdge
from doc_extractor.schemas.review import (
    QUALITY_CRITERIA,
    CriterionScore,
    DuplicateClass,
    DuplicateGroup,
    DuplicatePair,
    ReviewDecision,
    ValidationStatus,
)
from doc_extractor.schemas.state import (
    STAGE_ORDER,
    HumanReviewItem,
    PipelineState,
    ReviewItemKind,
    StageName,
    StageRecord,
    StageStatus,
    TraceRecord,
    merge_dict,
)

__all__ = [
    "QUALITY_CRITERIA",
    "STAGE_ORDER",
    "Attribute",
    "AttributeCandidate",
    "AttributeType",
    "BindingScope",
    "Block",
    "BlockKind",
    "CandidateOrigin",
    "CanonicalEntity",
    "Chunk",
    "CriterionScore",
    "Document",
    "DocumentFormat",
    "DocumentSummary",
    "DuplicateClass",
    "DuplicateGroup",
    "DuplicatePair",
    "Entity",
    "EntityBinding",
    "EntityOrigin",
    "Evidence",
    "FinalOutput",
    "HumanReviewItem",
    "Layer",
    "Mapping",
    "NormalizedEntity",
    "Optionality",
    "Page",
    "PipelineState",
    "Provenance",
    "RelationshipType",
    "ReviewDecision",
    "ReviewItemKind",
    "ReviewSection",
    "Route",
    "RunMetadata",
    "ScoreBreakdown",
    "SignalHit",
    "StageName",
    "StageRecord",
    "StageStatus",
    "StrictModel",
    "Table",
    "TraceEdge",
    "TraceRecord",
    "Unit",
    "ValidationStatus",
    "ValueDomain",
    "merge_dict",
]
